version: "3.8"

services:
  backend:
    image: backend-server
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/backend
      - /usr/src/backend/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

volumes:
  data:
